# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gNHmPUhA7upW_VWmOzYq57UiTd9PtY8V
"""

num=float(input())
kol=int(input())
print(round(num, kol))

n1=float(input())
n2=float(input())
sr=(n1+n2)/2
print(round(sr))