# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Siq1QEnVpsSEoAmIfImIsVd-rsyG9aCI
"""

num=int(input())
chet=num%2
if chet==0:
  print('Данное число четное')
else:
  print('Данное число не является четным')

num1=float(input()) #В задании не указанно, целые числа или нет. Если нужно, чтобы, если при вводе Int выводился тоже int, то после функции % на 2 внутрь оператора можно ввести еще одинБ который будет ее проверять и выводить нужный тип данных.
num2=float(input())
if num1>=num2:
  print(num1)
else:
  print(num2)

k,l=int(input()),int(input())#левый нижний угол черный
if (k+l)%2==0:
  print("NO")
else:
  print("YES")